sudo: required
services:
    - docker

before_install:
    - docker build -t tumenzul/react_test -f ./client/Dockerfile.dev ./client

script:
    - docker run tumenzul/react_test npm test -- --coverage

after_success:
    - docker build -t tumenzul/multi-client ./client
    - docker build -t tumenzul/multi-nginx ./nginx
    - docker build -t tumenzul/multi-server ./server
    - docker build -t tumenzul/multi-worker ./worker
    #  Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push tumenzul/multi-client
    - docker push tumenzul/multi-nginx
    - docker push tumenzul/multi-server
    - docker push tumenzul/multi-worker


deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-096013720088
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY